### ISSUE TITLE
Debloating Dockerfile

### ISSUE THREAD

**Issue by ptr1337** [pyavitz/arm-img-builder#8]
Since you provide for every Arch a own command for dependecies, the Dockerfile can be debloated and much smaller sized.

**Comment by pyavitz** [comment]
Sounds fine to me. Do whatever it is you think is best, sir.

**Comment by pyavitz** [comment]
We should also pull the armhf branch out of the docker image. The master branch now supports the 2B, making the armhf branch kind of pointless.

**Comment by pyavitz** [comment]
We need to update to Hirsute for the Clang bit to work correctly. I believe we can remove `make cross` and `make native` as the builders now detect what ur running on when you execute `./install`.

So if that's not a problem, I will change it to `make install` or something like this? As the two commands in my testing don't appear to be needed.

***Changes made so far:***
https://github.com/pyavitz/arm-img-builder/tree/build

**Comment by ptr1337** [comment]
Ill work on this evening on it. Sorry for being late.

**Comment by pyavitz** [comment]
Alright. I believe the changes I made should work now for both x86-64 and arm64. Just take note that when you make whatever needed adjustments to the docker/function file and merge everything with `main` that you also change the following lines in the file.

```sh
   && wget -cq --show-progress https://raw.githubusercontent.com/pyavitz/arm-img-builder/build/Makefile \
   && mkdir -p docker \
   && wget -cq --show-progress -P docker https://raw.githubusercontent.com/pyavitz/arm-img-builder/build/docker/update \
   && wget -cq --show-progress -P docker https://raw.githubusercontent.com/pyavitz/arm-img-builder/build/docker/function
```
`build` in those lines should be `main`.
